### ISSUE TITLE
Proofread docs

### ISSUE THREAD

**Issue by xintamosaik** [Nerds-Who-Code/feelsify.io#7]
It would be cool if we proof read our docs. 
Who is up to the task?

**Comment by treblig-punisher** [comment]
Hey, what docs are we talking about? I'd like to take a look.

**Comment by med4kat** [comment]
Hey, thanks for asking! The docs are here:
https://nerds-who-code.github.io/feelsify.io/

It would be great if you can have a look!

**Comment by treblig-punisher** [comment]
> 

Alright, I found a couple issues with the docs.

"In order to run the project locally, both client and server app needs to be running."
-Needs should be need.
 
"Server does not work with the browser The server has been designed to work with the client, not with the browser."
-I think you are missing a period after "Server does not work with the browser." Also, you are missing the article THE at the beginning of that sentence. 
 
"Here is are a list of people who contribute to the project. If you encounter any issues with the project, please contact: [list of people] "
 
- Here is are, should be Here is. 
- Other than that this looks fine so far!

**Comment by med4kat** [comment]
Thank you very much for your help!!!
Would you like to make changes by yourself and create a PR?

**Comment by treblig-punisher** [comment]
> Thank you very much for your help!!! Would you like to make changes by yourself and create a PR?

I'll make a PR once I make the changes. I keep forgetting to clone the repo and do a PR.
